### ISSUE TITLE
Location barcodes & generic scanners

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/JobTracking#9]
Currently I believe locations are set by the uid of a scanner being associated with a location, and anything scanned by this scanner gets assigned to its associated location. This makes sense when locations are far apart and the operators and scanners stay still. 

In some situations it would be preferable for all scanners to be equal, and an association between object and location to be made by scanning a code for each in quick succession. 

Imagine trying to keep track of the locations of boxes moving around a warehouse. Each shelf have a scanner next to it and the operative picking up the correct scanner to scan the box onto the shelf would be unfeasible, for reasons not limited to the thousands of scanners. Instead it would be more reasonable for each shelf to have a barcode, and each operative to have a scanner they keep with them.

**Comment by Greg-Hawkridge** [comment]
This can be done - it requires a replacement data collection service module - I have developed this for batch job tracking [Here](https://github.com/DigitalShoestringSolutions/sm_barcode_dc). You're welcome to have a go at replacing it

**Comment by tobyaharris** [comment]
Just checking what the plan for this is - the linked sm_barcode_dc gets the award for DigitalShoestrings's least active codebase: 
![image](https://github.com/DigitalShoestringSolutions/JobTracking/assets/51968582/3457bf10-8d0b-45b0-8e37-27f8919ad256)
It doesn't look like a drop in replacement, does a new solution need to be built around this module?

**Comment by Greg-Hawkridge** [comment]
Solved by new Job tracking (Location Tracking)
